app = 'apple-music-mcp'
primary_region = 'arn'

[build]

[env]
  PORT = '3000'
  APPLE_STOREFRONT = 'dk'
  SERVER_URL = 'https://music.broberg.dk'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
